import { useRef, useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Breadcrumbs from "@/components/Breadcrumbs";
import { Button } from "@/components/ui/button";
import { motion } from "framer-motion";
import { FileText, Download, Loader2, Share2, Image as ImageIcon } from "lucide-react";
import { toast } from "sonner";
import { useActiveProfile } from "@/hooks/useActiveProfile";
import { usePersonalization } from "@/hooks/usePersonalization";
import jsPDF from "jspdf";
import { toPng } from "html-to-image";

export default function ReportsPage() {
  const { active } = useActiveProfile();
  const { ctx } = usePersonalization();
  const [loading, setLoading] = useState(false);
  const [exporting, setExporting] = useState(false);
  const cardRef = useRef<HTMLDivElement>(null);

  const generate = () => {
    if (!active) { toast.error("Pick a profile first"); return; }
    setLoading(true);
    try {
      const d = active.farmer_details || {};
      const doc = new jsPDF();
      const W = doc.internal.pageSize.width;
      let y = 20;

      doc.setFillColor(34, 139, 73);
      doc.rect(0, 0, W, 30, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.text("KrishiMitra — Smart Farm Report", 14, 20);

      doc.setTextColor(0, 0, 0);
      y = 40;
      doc.setFontSize(14);
      doc.text(`Farmer: ${active.full_name}`, 14, y); y += 7;
      doc.setFontSize(10);
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, y); y += 10;

      const sec = (title: string) => { doc.setFontSize(12); doc.setFont("helvetica", "bold"); doc.text(title, 14, y); y += 6; doc.setFont("helvetica", "normal"); doc.setFontSize(10); };
      const line = (label: string, val: string) => { if (!val) return; doc.text(`${label}: ${val}`, 18, y); y += 5; if (y > 270) { doc.addPage(); y = 20; } };

      sec("📍 Location");
      line("State", d.state); line("District", d.district); line("Village", d.village);
      line("Farm Location", active.farm_location || "");
      y += 3;

      sec("🌱 Land & Soil");
      line("Total Land", `${d.total_land || "?"} acres`);
      line("Soil Type", active.soil_type || d.soil_color || "");
      line("Soil pH", d.soil_ph); line("N-P-K", `${d.nitrogen || "?"} / ${d.phosphorus || "?"} / ${d.potassium || "?"}`);
      line("Water Source", d.water_source); line("Irrigation", d.irrigation_type);
      y += 3;

      sec("🌾 Crops");
      line("Current", d.current_crops); line("Previous Season", d.previous_crops);
      line("Preferred Season", d.preferred_season); line("Farming Type", d.farming_type);
      line("Livestock", d.livestock);
      y += 3;

      sec("💰 Financial");
      line("Annual Income", d.annual_income); line("Monthly Investment", d.monthly_investment);
      line("Bank Account", d.bank_account); line("Insurance", d.insurance_status);
      line("Existing Loans", d.existing_loans);
      y += 3;

      if (ctx) {
        sec("🤖 AI Insights");
        line("Climate Zone", ctx.climate.zone);
        line("Current Season", ctx.climate.current_season);
        line("Monsoon Stage", ctx.climate.monsoon_stage);
        line("Suitable Crops", ctx.crops.suitable.join(", "));
        line("Schemes Matched", ctx.schemes_matched.join(", "));
        line("Farm Health Score", `${ctx.scores.farm_health}/100`);
        line("Soil Health Score", `${ctx.scores.soil_health}/100`);
      }

      y += 5;
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text("Generated by KrishiMitra AI · SIH 2025 · #25030", 14, 285);

      doc.save(`KrishiMitra_${active.full_name.replace(/\s+/g, "_")}_${Date.now()}.pdf`);
      toast.success("📄 Report downloaded! Use it for loans, insurance, or just to brag.");
    } catch (e: any) {
      toast.error("PDF generation failed: " + e.message);
    } finally { setLoading(false); }
  };

  return (
    <div className="min-h-screen bg-muted/30">
      <Navbar />
      <main className="pt-24 pb-12 px-4">
        <div className="container mx-auto max-w-3xl">
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
            <h1 className="text-2xl md:text-3xl font-display font-bold text-foreground flex items-center gap-2">
              <FileText className="h-7 w-7 text-primary" /> Smart Farm Reports
            </h1>
            <p className="text-muted-foreground mt-1">Generate a real PDF report of your farm — perfect for bank loans, insurance claims, or government applications</p>
          </motion.div>

          <div className="glass-card p-6">
            <h3 className="font-display font-semibold text-foreground mb-2">Your Farm Report Includes</h3>
            <ul className="text-sm text-muted-foreground space-y-1.5 mb-5 list-disc pl-5">
              <li>Personal & farm location details</li>
              <li>Soil composition & water resources</li>
              <li>Current crops, season, and farming style</li>
              <li>Financial profile & insurance status</li>
              <li>AI-generated insights, climate zone & schemes matched</li>
              <li>Farm health score (0-100)</li>
            </ul>
            <Button onClick={generate} disabled={loading || !active} className="w-full gradient-primary border-0 text-primary-foreground gap-2 h-12">
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
              {loading ? "Generating..." : "Download PDF Report"}
            </Button>
            <p className="text-xs text-muted-foreground mt-3 italic">💡 Pro tip: The more you fill in your profile, the richer your report. Currently using profile of <strong>{active?.full_name}</strong>.</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
