// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-mandi-prices.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var RESOURCE_ID = "9ef84268-d588-465a-a308-a864a43d0070";
var get_mandi_prices_default = defineTool({
  name: "get_mandi_prices",
  title: "Get mandi prices",
  description: "Fetch latest wholesale (mandi) prices for a crop from the Government of India data.gov.in API. Returns recent price records across mandis, optionally filtered by state.",
  inputSchema: {
    crop: z.string().min(1).describe("Commodity name, e.g. 'Onion', 'Wheat', 'Tomato'."),
    state: z.string().optional().describe("Optional Indian state name to filter by, e.g. 'Maharashtra'."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max records to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ crop, state, limit }) => {
    const apiKey = process.env.DATA_GOV_API_KEY;
    if (!apiKey) {
      return { content: [{ type: "text", text: "Mandi data service is not configured (missing DATA_GOV_API_KEY)." }], isError: true };
    }
    const call = async (withState) => {
      const u = new URL(`https://api.data.gov.in/resource/${RESOURCE_ID}`);
      u.searchParams.set("api-key", apiKey);
      u.searchParams.set("format", "json");
      u.searchParams.set("limit", String(limit));
      u.searchParams.set("filters[commodity]", crop);
      if (withState && state) u.searchParams.set("filters[state]", state);
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), 8e3);
      try {
        const r = await fetch(u.toString(), { signal: ctrl.signal });
        if (!r.ok) throw new Error(`data.gov.in ${r.status}`);
        return await r.json();
      } finally {
        clearTimeout(t);
      }
    };
    try {
      let data = await call(true);
      if (!data.records?.length && state) {
        try {
          data = await call(false);
        } catch {
        }
      }
      const records = data.records ?? [];
      const summary = records.length ? records.map((r) => `${r.market ?? "?"} (${r.state ?? "?"}) \u2014 ${r.commodity ?? crop} ${r.variety ?? ""}: modal \u20B9${r.modal_price ?? "?"} / min \u20B9${r.min_price ?? "?"} / max \u20B9${r.max_price ?? "?"} on ${r.arrival_date ?? "?"}`).join("\n") : `No mandi records found for ${crop}${state ? ` in ${state}` : ""}.`;
      return {
        content: [{ type: "text", text: summary }],
        structuredContent: { crop, state: state ?? null, count: records.length, records }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Failed to fetch mandi prices: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/get-daily-tip.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_daily_tip_default = defineTool2({
  name: "get_daily_farming_tip",
  title: "Get daily farming tip",
  description: "Return a short, practical daily farming tip for an Indian smallholder farmer, optionally personalized by location, soil, and current crops.",
  inputSchema: {
    language: z2.enum(["en", "hi", "bn", "ta", "te"]).default("en").describe("Response language code."),
    location: z2.string().optional().describe("Farm location (city / district / state)."),
    soil_type: z2.string().optional().describe("Soil type, e.g. 'black cotton', 'alluvial'."),
    current_crops: z2.string().optional().describe("Comma-separated list of crops currently grown.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ language, location, soil_type, current_crops }) => {
    const key = process.env.Groq_api_key_Rahul;
    const fallback = "Rotate crops every 2 seasons to keep soil nitrogen healthy.";
    if (!key) {
      return { content: [{ type: "text", text: fallback }], structuredContent: { tip: fallback, fallback: true } };
    }
    const farmerLine = `Indian smallholder farmer${location ? ` in ${location}` : ""}${soil_type ? `, soil: ${soil_type}` : ""}${current_crops ? `, crops: ${current_crops}` : ""}.`;
    try {
      const r = await fetch("https://api.groq.com/openai/v1/chat/completions", {
        method: "POST",
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "llama-3.3-70b-versatile",
          messages: [
            { role: "system", content: `Give ONE short practical farming tip (1 sentence, max 18 words) tailored for the user. Reply in language code: ${language}. No prefix, no emoji, just the tip.` },
            { role: "user", content: farmerLine }
          ],
          temperature: 0.8,
          max_tokens: 80
        })
      });
      const j = await r.json();
      const tip = j.choices?.[0]?.message?.content?.trim() || fallback;
      return { content: [{ type: "text", text: tip }], structuredContent: { tip } };
    } catch (e) {
      return { content: [{ type: "text", text: fallback }], structuredContent: { tip: fallback, fallback: true, error: e.message } };
    }
  }
});

// src/lib/mcp/tools/get-agri-news.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var CATEGORY_QUERY = {
  All: "Indian agriculture farmers",
  Technology: "Indian agriculture technology agritech",
  Policy: "Indian agriculture policy government scheme",
  Market: "Indian agriculture mandi market price",
  Research: "Indian agriculture research ICAR",
  Climate: "Indian agriculture climate weather monsoon",
  Success: "Indian farmer success story"
};
var LANG_MAP = {
  en: { hl: "en-IN", ceid: "IN:en" },
  hi: { hl: "hi", ceid: "IN:hi" },
  bn: { hl: "bn", ceid: "IN:bn" },
  ta: { hl: "ta", ceid: "IN:ta" },
  te: { hl: "te", ceid: "IN:te" }
};
function extract(xml, tag) {
  const m = xml.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`));
  if (!m) return "";
  return m[1].replace(/^<!\[CDATA\[|\]\]>$/g, "").trim();
}
var get_agri_news_default = defineTool3({
  name: "get_agri_news",
  title: "Get Indian agriculture news",
  description: "Fetch recent Indian agriculture news headlines from Google News RSS, filtered by category and language.",
  inputSchema: {
    category: z3.enum(["All", "Technology", "Policy", "Market", "Research", "Climate", "Success"]).default("All").describe("News category."),
    language: z3.enum(["en", "hi", "bn", "ta", "te"]).default("en").describe("Language code."),
    limit: z3.number().int().min(1).max(20).default(8).describe("Max articles to return.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ category, language, limit }) => {
    const q = CATEGORY_QUERY[category] ?? CATEGORY_QUERY.All;
    const lang = LANG_MAP[language] ?? LANG_MAP.en;
    const url = `https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=${lang.hl}&gl=IN&ceid=${lang.ceid}`;
    try {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`Google News ${r.status}`);
      const xml = await r.text();
      const items = xml.split("<item>").slice(1, limit + 1).map((chunk) => {
        const raw = "<item>" + chunk;
        return {
          title: extract(raw, "title"),
          url: extract(raw, "link"),
          date: extract(raw, "pubDate"),
          source: extract(raw, "source")
        };
      });
      const summary = items.length ? items.map((a, i) => `${i + 1}. ${a.title} \u2014 ${a.source} (${a.date})
   ${a.url}`).join("\n") : "No news articles found.";
      return { content: [{ type: "text", text: summary }], structuredContent: { category, language, articles: items } };
    } catch (e) {
      return { content: [{ type: "text", text: `Failed to fetch news: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "krishimate-mcp",
  title: "KrishiMate Hub MCP",
  version: "0.1.0",
  instructions: "Tools for Indian agriculture: fetch live mandi (wholesale) prices, get a personalized daily farming tip, and read recent Indian agriculture news headlines. Use these when the user asks about crop prices, market rates, farming advice, or agri news in India.",
  tools: [get_mandi_prices_default, get_daily_tip_default, get_agri_news_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
